---
- name: Validate mandatory secret variables
  assert:
    that:
      - vault_cloud1_db_root_password is defined
      - vault_cloud1_db_root_password | length > 0
      - vault_cloud1_db_password is defined
      - vault_cloud1_db_password | length > 0
      - vault_cloud1_wp_admin_email is defined
      - vault_cloud1_wp_admin_email | length > 0
    fail_msg: >-
      Missing secrets. Define required values in group_vars/all/vault.yml
      and encrypt it with ansible-vault.
