---
- name: Install baseline packages
  apt:
    name:
      - ufw
      - openssl
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: true

- name: Set default firewall incoming policy to deny
  command: ufw default deny incoming
  register: ufw_default_in
  changed_when: "'Skipping' not in ufw_default_in.stdout"

- name: Set default firewall outgoing policy to allow
  command: ufw default allow outgoing
  register: ufw_default_out
  changed_when: "'Skipping' not in ufw_default_out.stdout"

- name: Allow SSH
  command: ufw allow 22/tcp
  register: ufw_ssh
  changed_when: "'Skipping' not in ufw_ssh.stdout"

- name: Allow HTTP
  command: ufw allow 80/tcp
  register: ufw_http
  changed_when: "'Skipping' not in ufw_http.stdout"

- name: Allow HTTPS
  command: ufw allow 443/tcp
  register: ufw_https
  changed_when: "'Skipping' not in ufw_https.stdout"

- name: Ensure firewall is enabled
  command: ufw --force enable
  register: ufw_enable
  changed_when: "'already active' not in ufw_enable.stdout"
