- name: restart nginx
  command: docker compose restart nginx
  args:
    chdir: "{{ app_dir }}"

- name: Setup Let's Encrypt auto-renewal
  cron:
    name: "certbot renew"
    minute: "30"
    hour: "3"
    user: root
    job: >
      certbot renew --quiet &&
      cp /etc/letsencrypt/live/{{ domain_name }}/fullchain.pem {{ app_dir }}/nginx/ssl/cert.pem &&
      cp /etc/letsencrypt/live/{{ domain_name }}/privkey.pem {{ app_dir }}/nginx/ssl/key.pem &&
      docker compose -f {{ app_dir }}/docker-compose.yml restart nginx